### ISSUE TITLE
SAD

### ISSUE THREAD

**Issue by YuzhouWang999** [umautobots/SAD-GS#1]
where is shape alined?

**Comment by kungfrank** [comment]
It's mainly in `tarin.py`. Our sad-gs is enable when `args.cls_loss=True`. You can check the code for more details.

**Comment by tnttntailian** [comment]
> It's mainly in `tarin.py`. Our sad-gs is enable when `args.cls_loss=True`. You can check the code for more details.

Okay I see, thanks

**Comment by tnttntailian** [comment]
Do you have any mod changes to the submodules? For example, forward.cu and backward.cu?

**Comment by tnttntailian** [comment]
Do you have any changes to the package of submodules? For example, forward.cu and backward.cu?
